<?php
require_once('functions.php');
security_check();
?>
<div class="twelve columns">
<h3>Istoria anilor 1951 / 1960</h3>
<p>In perioada 1951-1961 apare prima echipa "martiana"! Don Santiago aduce la Madrid o gramada de "martieni" ca Di Stefano, Kopa, Gento, Puskas, Rial, Molowny, Lesmes, Santamaria etc. Pe bani multi dar sa faca spectacol si sa arate lumii întregi de ce a construit acel stadion. Acesti "martieni" jucau altceva, ceva ce nimeni nu vazuse pana atunci, ceva din alta galaxie, din alta dimensiune. Di Stefano si compania au scris istorie in acele vremuri au castigat 6 campionate din 10! Celelalte au fost împartite de Barca 3 si Athletic 1. Aici trebuie mentionat ca din cele 4 pierdute, 2 le-am pierdut în fata catalanilor (din care unul la golaveraj la diferentã de 2 goluri, noi avind 96-36 si ei 86-28! si ce atac aveam noi !). Ce greu trebuie sã fi fost pentru fanii merengue de atunci sã piarda un asemenea titlu la mustata.</p>
<img src="images/pics/images.jpg" width="250" height="380" alt="images.jpeg" class="center" />
<p>Unul dintre componentii de bazã ai echipei din acea perioada a fost Francesco "Paco" Gento. Paco Gento este de departe cel mai important mijlocas stanga din istoria clubului si unul dintre cei mai mari fotbalisti din toate timpurile. Cumparat in 1953 Paco avea sa ajunga o legenda a Realului, iar alaturi de alti mari jucatori ca Di Stefano, Puskas sau Kopa va marca o perioada irepetabila in istoria clubului madrilen, datorita trofeelor si faimei rezultate. Aripa stanga madrilena ajunge faimoasa în toata Europa ca urmare a evolutiilor în Cupa Campionilor, unde Gento a reusit performante fantastice: a evoluat in 8 finale ale faimoasei competitii, castigand 6 (in 1956, 1957, 1958, 1959, 1960 si 1966) un record absolut inca neegalat.</p>
<img src="images/pics/images1.jpg" width="250" height="380" alt="images1.jpeg" class="center" />
<p>Alfredo di Stefano este cel mai mare fotbalist din istoria clubului Real Madrid, dar e considerat de multi cunoscatori de fotbal, ca fiind cel mai bun jucator al tuturor timpurilor. Peste 5 milioane de pesetas a platit Bernabeu pentru a-l aduce la Madrid inaintea Barcelonei. N-a gresit, pentru ca Don Alfredo n-are egal în istoria blanco. Pele il considera cel mai mare fotbalist din toate timpurile. La fel si Crujff. Di Stéfano este de asemenea golgheterul lui Real Madrid din toate timpurile in campionat, cu 216 goluri in 282 de meciuri intre 1953 si 1964. A castigat de 8 ori campionatul Spaniol, cupa Spaniei, Cupa Intercontinentalã, si Cupa Campionilor de cinci ori. A fost fotbalistul anului în 1957 si 1959 cand a primit si Balonul de Aur în doua randuri. In total a marcat de 256 de ori în toate competiþiile pentru Real Madrid în 332 de partide oficiale, si este de departe cel mai valoros nume din istoria echipei.</p>
<img src="images/pics/images2.jpg" width="250" height="380" alt="images2.jpg" class="center" />
<p>Ferenc Puskas este vazut drept golgeterul absolut al fotbalului mondial. Omul care putea marca din orice pozitie a ajuns la Real Madrid în 1958. În sase ani a marcat 160 de goluri adica o medie de 30 pe sezon intr-o perioadã în care se jucau maxim 30 de meciuri in Spania. A castigat la Real Madrid trei Cupe ale Campionilor Europeni, 5 titluri de campion al Spaniei, Cupa Intercontinentala, Cupa Spaniei. La primul sau sezon la Madrid a marcat patru hattrickuri unul chiar la cel de-al doilea meci in alb. A fost golgeterul Spaniei timp de patru ani si a adus Cupa Regelui dupã ce a reusit dubla cu Sevilla. Este unul din cei mai mari fotbalisti all time.</p>

<h3>Istoria anilor 1961 / 1970</h3>
<p>Urmeaza anii 61-70 care ne oferã un alt Real frumos dar nu cel plin de "martieni" ci un Real Madrid ye-ye, Don Santiago stiind sa faca tranzitia de la martieni la "ye-ye -isti". Avem de a face cu noul Madrid, acesta este primul Madrid adevarat. Acum se pun bazele spiritului madrilen, acum cu o echipa muncitoare cu 2-3 varfuri de calitate pe ici pe colo reusim sã castigam 7 editii din 10! Celelalte trei fiind castigate de Valencia 1 si Atletico 2. Aceasta echipa inseamna baza madridismului! de aici se trage puterea urmatoarelor generatii. Aveam o echipa de luptatori, Pirri, Zocco, Gento, Grosso, Amancio, Santamaria, Sanchis, Velazquez. Acestia nu câstigau din talent ca generatia martienilor ci prin munca si sacrificiu</p>
<img src="images/pics/images1.jpg" width="250" height="380" alt="images1.jpg" class="center" />
<p>Jose Martinez Sanchez Pirri este unul dintre cei mai mari fotbalisti din istoria clubului madrilen. Nascut la Ceuta, Pirri a venit la Real in 1964 si a jucat timp de 15 ani in 440 de meciuri marcand 129 de goluri. 41 de selectii in nationala iberica, 10 titluri de campion al Spaniei, 4 Cupe si Cupa Campionilor în 1966 cu legendarul Real Madrid Ye Ye. S-a retras si si-a luat diploma de doctor, ramanand in stafful echipei madrilene. Este unul dintre cei mai importanti fotbalisti din istoria acestei echipe, evoluand la nevoie si ca libero sau fundas central. Elegant, puternic si foarte important în teren dar si in afara lui, Pirri a fost mereu un lider, un jucator determinat si determinant.</p>

<h3>Istoria anilor 1971 / 1980</h3>
<p>Anii 71-80 au fost ca o continuare a anilor 61-70 cu o mentiune: acesti ani fiind cei mai slabi la nivel international în timp ce Primera era un campionat modest. Pe atunci Germania, Olanda, Anglia faceau legea ca si la inceputul anilor 80. Echipa nu avea mari talente dar a pastrat aceeasi atitudine de muncã si sacrificiu. Real castigã 6 din cele 10 titluri, iar Barca 1 ca si Real Sociedad. In schimb Atletico cucereste doua titluri de campioana. Echipa noastra se baza in acele timpuri pe jucaori ca: Pirri si Zocco (in continuare Zocco find retras fundas), Santillana, Amancio, Breitner, Del Bosque, Stielike, Camacho, Juanito, Angel. Frumoase timpuri nostalgice ne apropiem incet, incet de epoca televizorului color Castilla da echipei mari 5 fotbalisti care vor forma "Quinta lui Butre". In acesti ani se formeaza un alt tip de Real, mai combinativ, mai ofensiv, dar cu aceleasi valori si cu cu acelasi spirit "Quinta lui Butre" este Realul care a fermecat suporterii.</p>
<img src="images/pics/images3.jpg" width="250" height="380" alt="images3.jpg" class="center" />
<p>Michel este legendar. S-a nascut la Madrid si a venit la Real la 13 ani. A jucat începând cu 1976 pana in 1996 la gruparea blanco, 20 de ani la toate nivelurile pentru Jose Miguel Martin del Campo "Michel" unul dintre cei mai importanti fotbalisti din istoria clubului. Are 450 de meciuri in toate competitiile la Real Madrid si 102 goluri. Unul dintre componentii La Quinta del Butre, Michel a castigat de doua ori Cupa Uefa, 6 titluri de campion, 3 Cupe ale Spaniei, o Cupa a ligii si 4 Supercupe ale Spaniei fiind mijlocasul dreapta cu cele mai multe goluri marcate în Primera Division în istoria fotbalului spaniol. Pentru nationala iberica a evoluat in 66 de meciuri si a marcat 21 de goluri.</p>
<img src="images/pics/images4.jpg" width="250" height="380" alt="images4.jpg" class="center" />
<p>Paul Breitner este unul dintre jucatorii germani care au triumfat la Real Madrid. N-au fost multi, dar au fost mari. A venit în 1974 si a jucat peste tot. si în stanga si in dreapta si la inchidere chiar si fundas. Un fotbalist extraordinar crescut de Bayern Munchen, un stangaci fantastic, luptator si inteligent. La Real Madrid a câstigat douã titluri de campion si o Cupa a Regelui Spaniei, marcand în 85 de meciuri de 11 ori.</p>
<img src="images/pics/images5.jpg" width="250" height="380" alt="images5.jpg" class="center" />
<p>Jose Antonio Camacho este o legenda. 414 meciuri jucate in tricoul lui Real Madrid pentru fundasul stanga care a debutat în 1974 la madrileni si s-a retras peste 15 ani. Are 82 de meciuri in nationala iberica si este considerat cel mai bun fundas stanga din istoria Spaniei. Ca jucator a castigat de doua ori Cupa Uefa cu Real Madrid, 5 Cupe ale Spaniei, doua Supercupe, o Cupa a Ligii dar si 9 titluri de campion al Spaniei. Adunand meciurile din Cupele Europene, Camacho a strans peste 500 de meciuri oficiale în tricoul lui Real Madrid.</p>

<h3>Istoria anilor 1981 / 1990</h3>
<p>Anii 81-90 ani marcati in Spania de o echipa iesita de nicaieri dintr-o echipa filiala (RM Castilia). Castilla da echipei mari 5 fotbalisti care vor forma "quinta lui Butre"! Mai precis Butragueno, Manolo Sanchís, Martín Vázquez, Míchel si Miguel Pardeza. In acesti ani se formeaza un alt tip de Real, mai combinativ mai ofensiv, dar cu aceleasi valori cu acelasi spirit. Realul castiga 5 campionate la rand, Atletico 2, Barca 2, Real Sociedad 1. "Quinta lui Butre" este Realul care a fermecat suporterii de pretutideni. Ca fapt divers aceasta echipa, intr-un sondaj facut în Spania de catre ambele cotidiene din Madrid..a iesit ca cea mai iubita echipa a Realului din toate timpurile!</p>
<img src="images/pics/images6.jpg" width="250" height="380" alt="images6.jpg" class="center" />
<p>Emilio Butragueno nu mai are nevoie de nicio prezentare. Unul dintre cei mai mari fotbalisti spanioli si unul dintre cei mai mari fotbalisti ai Realului din toate timpurile. Butre a dat nastere unui curent si a petrecut la Real Madrid 14 ani doar ca fotbalist. In 350 de meciuri a marcat de 135 de ori pentru Real Madrid trecand in palmaresul sau Cupa UEFA de doua ori, 6 titluri de campion, Cupa Spaniei de doua ori, Supercupa Spaniei in patru randuri. A fost golgeter al Spaniei, si al doilea cel mai bun jucator din lume în 1986 dupa Maradona.</p>
<img src="images/pics/images8.jpg" width="250" height="380" alt="images8.jpg" class="center" />
<p>Hugo Sanchez este incontestabil unul din marii atacanti ai fotbalului mondial. Sapte ani a jucat la Real Madrid iar cifrele sale sunt incredibile. 170 de goluri marcate in 209 meciuri de catre atacantul nascut la Mexico City. Hugo Sanchez a sosit in 1985 la Madrid si a facut parte din poate cea mai spectaculoasa echipa din istoria clubului. A fost foarte iubit de fani la Madrid unde a castigat 5 tiluri de campion al Spaniei, Cupa Regelui, Supercupa Spaniei dar si cinci titluri de golgeter al Primerei. A fost Gheata de Aur a Europei si unul din cei mai buni 100 de fotbalisti din toate timpurile. Cel mai bun sportiv din Mexic in Secolul 20!</p>
<img src="images/pics/images7.jpg" width="250" height="380" alt="images7.jpg" class="center" />
<p>Rafa Martin Vasquez a fost component al Quintei del Butre si unul dintre cei mai valorosi jucatori crescuti de Real Madrid vreodata. S-a nascut la Madrid si a jucat la Real Madrid incepand cu 1980. A debutat pentru Castilla pentru ca in 1983 sa treaca la prima echipa unde a jucat sapte ani. Ulterior a plecat în Italia si Franta pentru a se intoarce în 1992 si a mai juca alti trei ani. In 270 de meciuri pentru Real Madrid a marcat 49 de goluri si si-a servit impecabil colegii cu numeroase pase de gol. De 40 de ori international spaniol, Rafa a cucerit la Real Madrid douã Cupa UEFA, 6 titluri de campion, doua Cupe, trei Supercupe si o Cupa a Ligii.</p>

<h3>Istoria anilor 1991 / 2000</h3>
<p>Anii 91-00 au adus primii nori negri deasupra Realului, doar sfirsitul acestor ani si cele 2 UCL au mai salvat situatia. Am castigat doar 3 campionate iar Dream-Teamul lui Cruyff cinci ! Unul Atletico si unul Super Depor. Au fost primii ani intradevar grei de la razboi incoace. Le facem cadou catalanilor 2 campionate în Tenerife, dar ce trebuie mentionat aici... Cele doua UCL, plus investitiile in terenuri care le va face Lorenzo Sanz la sfârsitul anilor 90 ne aduc nouã si astazi stabilitate financiara, pe care nu o are nimeni in aceasta lume fotbalistica. Sanz cumpara terenuri care nici astazi nu sunt vandute si pune si bazele Realului Galactic ce va urma. A procedat cam asa cum a facut Don Santiago dupa razboi pastrand proporþiile evident.</p>
<img src="images/pics/images9.jpg" width="250" height="380" alt="images9.jpg" class="center" />
<p>Ivan Zamorano a sosit in 1992 la Real Madrid si in patru ani de zile a fost principalul marcator al echipei. Sud americanul marca de 77 de ori în 137 de meciuri pentru Los Merengues castigand Cupa Spaniei, Supercupa Spaniei si titlul in sezonul 1994-1995 cand a fost si golgeterul sezonului. Este unul dintre marcatorii inascuti ai clubului Real Madrid.</p>
<img src="images/pics/images11.jpg" width="250" height="380" alt="images11.jpg" class="center" />
<p>Michael Laudrup a fost unul dintre cei mai buni fotbalisti din toate timpurile. A jucat la Real Madrid doar doi ani, venind de la FC Barcelona. In 70 de meciuri a inscris 15 goluri dar a fost extrem de apreciat. A plecat in Japonia la Vissel Kobe pentru a se retrage dupa ce a contribuit la titlul din sezonul 1994. Este considerat cel mai bun fotbalist danez din toate timpurile si unul dintre cei mai valorosi care au jucat vreodata in Primera Division. Figo spunea despre el: "A fost cel mai bun fotbalist impotriva caruia am jucat vreodata" in timp ce Iniesta l-a laudat si el: "Cel mai bun fotbalist din lume? Laudrup!"</p>
<img src="images/pics/images10.jpg" width="250" height="380" alt="images10.jpg" class="center" />
<p>Davor Suker a sosit la Real Madrid in 1996 de la Sevilla. A impresionat rapid si a devenit titular. Fotbalistul nascut la Osijek a înscris in trei ani pe Bernabeu 44 de goluri în 94 de meciuri pentru Real Madrid trecandu-si în palmares un titlu de campion, Supercupa Spaniei, Liga Campionilor si Cupa Intercontinentala. În sezonul 1996-1997 a fost golgeterul lui Real Madrid.</p>

</div>

